### ISSUE TITLE
Nginx error on default docker run

### ISSUE THREAD

**Issue by diogomonica** [centminmod/docker-nginx-mini#1]
Following the instructions (`docker run ...` ) my container comes up but the NGINX fails to parse the config:

``` sh
[root@5229609a3040 nginx]# cat error.log
2015/05/31 19:47:02 [emerg] 15#15: unknown directive "[root@0049f0cf5363" in /etc/nginx/fastcgi_params:40
```

Editing manually `/etc/nginx/fastcgi_params` and removing that line (not sure how it gets there), fixes the problem.

**Comment by centminmod** [comment]
thanks @diogomonica haven't looked at this docket image in while didn't know I made a boo boo..

updated fix at https://github.com/centminmod/docker-nginx-mini/commit/a4f5600453bf2ce11e1ecbad4640ce7b86c0d5c8
